"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from os.path import dirname, join, abspath


def str2bool(in_str):
    return in_str in ['true', 'True', 'yes']


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = abspath(join(dirname(os.path.abspath(__file__)), '..', '..'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qbfp*@h$(g!4)cv7f8c#jz+3tn7rcn2y=_*kq!k60s=yfq_4m7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str2bool(os.getenv('DJANGO_DEBUG', 'true'))

ALLOWED_HOSTS = []


ROOT_URLCONF = 'web.urls'

WSGI_APPLICATION = 'web.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static"),
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, "static")

STATIC_URL = '/static/'
